### ISSUE TITLE
How to port to a different RTOS?

### ISSUE THREAD

**Issue by amalabey** [intel/wasm-micro-runtime#121]
Can you provide some guidance/documentation on how to enable support to another RTOS (e.g. FreeRTOS)? I got the runtime working with Zephyr on ESP32, but unfortunately, I can't get the WIFI working because ESP-IDF uses FreeRTOS.

**Comment by wenyongh** [comment]
Hi, suppose the platform directory name is freertos, there are three folders to be created:
(1) core/shared/platform/freertos
   files: bh_platform.h/c, bh_assert.c, bh_definition.c, bh_platform_log.c,
           bh_time.c bh_thread.c,
           bh_match.c(if some math functions are not supported by FreeRTOS)
(2) core/iwasm/runtime/platform/freertos
    file: wasm_native.c with function wasm_platform_native_func_lookup(),
          which normally just returns NULL.
(3) core/iwasm/products/freertos
    files: main.c, ext_lib_export.c and makefile e.g. CMakeLists.txt

Could you ref to the implementation of other platforms e.g. Linux and Zephyr?

**Comment by amalabey** [comment]
Thanks, appreciate the quick response!

**Comment by vshymanskyy** [comment]
@amalabey did you get the wifi working?

**Comment by amalabey** [comment]
Sorry, no it turned out to be too much work to support FreeRtos and couldn’t complete.

**Comment by vshymanskyy** [comment]
@amalabey you might be interested in this https://github.com/bytecodealliance/wasm-micro-runtime/issues/134#issuecomment-571178221
