### ISSUE TITLE
WAMR relicensing coordination

### ISSUE THREAD

**Issue by joshtriplett** [intel/wasm-micro-runtime#123]
WAMR is currently licensed under the Apache 2.0 license. To better collaborate with other projects like wasmtime, cranelift, lucet, and LLVM, Intel would like to match the license of those projects, which use the [Apache 2.0 license with LLVM exception](https://llvm.org/docs/DeveloperPolicy.html#new-llvm-project-license-framework). The LLVM exception keeps all the properties of the Apache 2.0 license, and improves license compatibility.

In order to make this change, we need your help; we're seeking permission from the non-Intel contributors to WAMR to make this change. The following people have made contributions to WAMR:

- [x] @zhujinzhou
- [x] @yiting16
- [x] @beriberikix
- [x] @jondong
- [x] @0xflotus
- [ ] @hakilebara
- [x] @pcmill
- [ ] @offercomes

If this seems reasonable to you, could you please respond to this issue with a comment? (Just saying "sure" is fine; we'll coordinate the list.)

Once we have approval from the folks listed above, I'll post a PR adding the LLVM exception text to the license.

Thank you again for your contributions to WAMR!

**Comment by beriberikix** [comment]
Sure! Glad to see the collaboration 😁

**Comment by 0xflotus** [comment]
Sure :)

**Comment by yiting16** [comment]
Sure.

**Comment by jondong** [comment]
Sure! nice to see the collaboration

**Comment by zhujinzhou** [comment]
sure!!!

**Comment by pcmill** [comment]
Sure, I just made some changes to the README :smiley:

**Comment by joshtriplett** [comment]
Fixed in #137.
