### ISSUE TITLE
Dockerfile for development

### ISSUE THREAD

**Issue by beriberikix** [intel/wasm-micro-runtime#44]
I put together a simple `Dockerfile` so that I can easily develop on my macOS machine, found here: https://github.com/beriberikix/wamr-docker

Is there any interest in including it? I added the `test.c` from the `README` since it isn't in the main repo, but can easily remove it before merging.

**Comment by xwang98** [comment]
It would be nice! Could you please advise how to include it?

**Comment by beriberikix** [comment]
I created #97 with an a file that supports clang and updates to the README. Please leave comments in the PR if you need any corrections!

**Comment by beriberikix** [comment]
Closing with #97
