### ISSUE TITLE
 There is no iwasm/products/linux/bin directory

### ISSUE THREAD

**Issue by darkmoon233** [intel/wasm-micro-runtime#46]
There is no iwasm/products/linux/bin directory, iwasm directory is iwasm/products/linux/build/iwasm.
This is inconsistent with the description in the readme documentation:
```
cd iwasm/products/linux/bin
./iwasm test.wasm
```

**Comment by wenyongh** [comment]
Yes, thanks a lot @darkmoon233, we will modify it soon.

**Comment by wenyongh** [comment]
readme has been updated.
